services:
  postgres:
    image: postgres:15-alpine
    container_name: nuxt_starter_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    # restart: unless-stopped # You can uncomment this if you want the DB to restart automatically

# volumes: # Define the named volume if you prefer it over host-mounted
#   pgdata:
